//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neutrino.External.Sevices.neu.eliteco.services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class CompanyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName {
            get {
                return this.EnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnNameField, value) != true)) {
                    this.EnNameField = value;
                    this.RaisePropertyChanged("EnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaName {
            get {
                return this.FaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FaNameField, value) != true)) {
                    this.FaNameField = value;
                    this.RaisePropertyChanged("FaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class GoodsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConsumerPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenericField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenericCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasExtraChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasTaxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTechnicalApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfficalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PackageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProducerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PurchasePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Neutrino.External.Sevices.neu.eliteco.services.SupplierTypes SupplierTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ConsumerPrice {
            get {
                return this.ConsumerPriceField;
            }
            set {
                if ((this.ConsumerPriceField.Equals(value) != true)) {
                    this.ConsumerPriceField = value;
                    this.RaisePropertyChanged("ConsumerPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName {
            get {
                return this.EnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnNameField, value) != true)) {
                    this.EnNameField = value;
                    this.RaisePropertyChanged("EnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaName {
            get {
                return this.FaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FaNameField, value) != true)) {
                    this.FaNameField = value;
                    this.RaisePropertyChanged("FaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Generic {
            get {
                return this.GenericField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericField, value) != true)) {
                    this.GenericField = value;
                    this.RaisePropertyChanged("Generic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenericCode {
            get {
                return this.GenericCodeField;
            }
            set {
                if ((this.GenericCodeField.Equals(value) != true)) {
                    this.GenericCodeField = value;
                    this.RaisePropertyChanged("GenericCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsCode {
            get {
                return this.GoodsCodeField;
            }
            set {
                if ((this.GoodsCodeField.Equals(value) != true)) {
                    this.GoodsCodeField = value;
                    this.RaisePropertyChanged("GoodsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasExtraCharge {
            get {
                return this.HasExtraChargeField;
            }
            set {
                if ((this.HasExtraChargeField.Equals(value) != true)) {
                    this.HasExtraChargeField = value;
                    this.RaisePropertyChanged("HasExtraCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasTaxable {
            get {
                return this.HasTaxableField;
            }
            set {
                if ((this.HasTaxableField.Equals(value) != true)) {
                    this.HasTaxableField = value;
                    this.RaisePropertyChanged("HasTaxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTechnicalApproved {
            get {
                return this.IsTechnicalApprovedField;
            }
            set {
                if ((this.IsTechnicalApprovedField.Equals(value) != true)) {
                    this.IsTechnicalApprovedField = value;
                    this.RaisePropertyChanged("IsTechnicalApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficalCode {
            get {
                return this.OfficalCodeField;
            }
            set {
                if ((this.OfficalCodeField.Equals(value) != true)) {
                    this.OfficalCodeField = value;
                    this.RaisePropertyChanged("OfficalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackageCount {
            get {
                return this.PackageCountField;
            }
            set {
                if ((this.PackageCountField.Equals(value) != true)) {
                    this.PackageCountField = value;
                    this.RaisePropertyChanged("PackageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProducerId {
            get {
                return this.ProducerIdField;
            }
            set {
                if ((this.ProducerIdField.Equals(value) != true)) {
                    this.ProducerIdField = value;
                    this.RaisePropertyChanged("ProducerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchasePrice {
            get {
                return this.PurchasePriceField;
            }
            set {
                if ((this.PurchasePriceField.Equals(value) != true)) {
                    this.PurchasePriceField = value;
                    this.RaisePropertyChanged("PurchasePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesPrice {
            get {
                return this.SalesPriceField;
            }
            set {
                if ((this.SalesPriceField.Equals(value) != true)) {
                    this.SalesPriceField = value;
                    this.RaisePropertyChanged("SalesPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Neutrino.External.Sevices.neu.eliteco.services.SupplierTypes SupplierType {
            get {
                return this.SupplierTypeField;
            }
            set {
                if ((this.SupplierTypeField.Equals(value) != true)) {
                    this.SupplierTypeField = value;
                    this.RaisePropertyChanged("SupplierType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierTypes", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    public enum SupplierTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Domestic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Foreign = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsCat", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class GoodsCat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsId {
            get {
                return this.GoodsIdField;
            }
            set {
                if ((this.GoodsIdField.Equals(value) != true)) {
                    this.GoodsIdField = value;
                    this.RaisePropertyChanged("GoodsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsCatType", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class GoodsCatType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class BranchInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Zone {
            get {
                return this.ZoneField;
            }
            set {
                if ((this.ZoneField.Equals(value) != true)) {
                    this.ZoneField = value;
                    this.RaisePropertyChanged("Zone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class MemberInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ccgorohField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ccpostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamePost {
            get {
                return this.NamePostField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePostField, value) != true)) {
                    this.NamePostField = value;
                    this.RaisePropertyChanged("NamePost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode {
            get {
                return this.NationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalCodeField, value) != true)) {
                    this.NationalCodeField = value;
                    this.RaisePropertyChanged("NationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ccgoroh {
            get {
                return this.ccgorohField;
            }
            set {
                if ((this.ccgorohField.Equals(value) != true)) {
                    this.ccgorohField = value;
                    this.RaisePropertyChanged("ccgoroh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ccpost {
            get {
                return this.ccpostField;
            }
            set {
                if ((this.ccpostField.Equals(value) != true)) {
                    this.ccpostField = value;
                    this.RaisePropertyChanged("ccpost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchSalesInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class BranchSalesInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalTedadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsId {
            get {
                return this.GoodsIdField;
            }
            set {
                if ((this.GoodsIdField.Equals(value) != true)) {
                    this.GoodsIdField = value;
                    this.RaisePropertyChanged("GoodsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalTedad {
            get {
                return this.TotalTedadField;
            }
            set {
                if ((this.TotalTedadField.Equals(value) != true)) {
                    this.TotalTedadField = value;
                    this.RaisePropertyChanged("TotalTedad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class InvoiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsId {
            get {
                return this.GoodsIdField;
            }
            set {
                if ((this.GoodsIdField.Equals(value) != true)) {
                    this.GoodsIdField = value;
                    this.RaisePropertyChanged("GoodsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payroll", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class Payroll : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PaymentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MandehFaktor", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class MandehFaktor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodemoshtaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameMoshtaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShomarehFaktorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TarikhFaktorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ccForoshandehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ccafradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ccmarkazpakhshField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> mablaghmandehmoshtaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namegorohField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codemoshtary {
            get {
                return this.CodemoshtaryField;
            }
            set {
                if ((object.ReferenceEquals(this.CodemoshtaryField, value) != true)) {
                    this.CodemoshtaryField = value;
                    this.RaisePropertyChanged("Codemoshtary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameMoshtary {
            get {
                return this.NameMoshtaryField;
            }
            set {
                if ((object.ReferenceEquals(this.NameMoshtaryField, value) != true)) {
                    this.NameMoshtaryField = value;
                    this.RaisePropertyChanged("NameMoshtary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShomarehFaktor {
            get {
                return this.ShomarehFaktorField;
            }
            set {
                if ((this.ShomarehFaktorField.Equals(value) != true)) {
                    this.ShomarehFaktorField = value;
                    this.RaisePropertyChanged("ShomarehFaktor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TarikhFaktor {
            get {
                return this.TarikhFaktorField;
            }
            set {
                if ((this.TarikhFaktorField.Equals(value) != true)) {
                    this.TarikhFaktorField = value;
                    this.RaisePropertyChanged("TarikhFaktor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ccForoshandeh {
            get {
                return this.ccForoshandehField;
            }
            set {
                if ((this.ccForoshandehField.Equals(value) != true)) {
                    this.ccForoshandehField = value;
                    this.RaisePropertyChanged("ccForoshandeh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ccafrad {
            get {
                return this.ccafradField;
            }
            set {
                if ((this.ccafradField.Equals(value) != true)) {
                    this.ccafradField = value;
                    this.RaisePropertyChanged("ccafrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ccmarkazpakhsh {
            get {
                return this.ccmarkazpakhshField;
            }
            set {
                if ((this.ccmarkazpakhshField.Equals(value) != true)) {
                    this.ccmarkazpakhshField = value;
                    this.RaisePropertyChanged("ccmarkazpakhsh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> mablaghmandehmoshtary {
            get {
                return this.mablaghmandehmoshtaryField;
            }
            set {
                if ((this.mablaghmandehmoshtaryField.Equals(value) != true)) {
                    this.mablaghmandehmoshtaryField = value;
                    this.RaisePropertyChanged("mablaghmandehmoshtary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namegoroh {
            get {
                return this.namegorohField;
            }
            set {
                if ((object.ReferenceEquals(this.namegorohField, value) != true)) {
                    this.namegorohField = value;
                    this.RaisePropertyChanged("namegoroh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberReceiptInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class MemberReceiptInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceiptAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReceiptAmount {
            get {
                return this.ReceiptAmountField;
            }
            set {
                if ((this.ReceiptAmountField.Equals(value) != true)) {
                    this.ReceiptAmountField = value;
                    this.RaisePropertyChanged("ReceiptAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchReceiptInfo", Namespace="http://schemas.datacontract.org/2004/07/Elite.Neutrino.Services")]
    [System.SerializableAttribute()]
    public partial class BranchReceiptInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceiptAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceiptAmountKhoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReceiptAmount {
            get {
                return this.ReceiptAmountField;
            }
            set {
                if ((this.ReceiptAmountField.Equals(value) != true)) {
                    this.ReceiptAmountField = value;
                    this.RaisePropertyChanged("ReceiptAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReceiptAmountKho {
            get {
                return this.ReceiptAmountKhoField;
            }
            set {
                if ((this.ReceiptAmountKhoField.Equals(value) != true)) {
                    this.ReceiptAmountKhoField = value;
                    this.RaisePropertyChanged("ReceiptAmountKho");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="neu.eliteco.services.IEliteService")]
    public interface IEliteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetCompanies", ReplyAction="http://tempuri.org/IEliteService/GetCompaniesResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.CompanyInfo[] GetCompanies(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetCompanies", ReplyAction="http://tempuri.org/IEliteService/GetCompaniesResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.CompanyInfo[]> GetCompaniesAsync(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoods", ReplyAction="http://tempuri.org/IEliteService/GetGoodsResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.GoodsInfo[] GetGoods(string userName, string password, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoods", ReplyAction="http://tempuri.org/IEliteService/GetGoodsResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsInfo[]> GetGoodsAsync(string userName, string password, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoodsCategory", ReplyAction="http://tempuri.org/IEliteService/GetGoodsCategoryResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.GoodsCat[] GetGoodsCategory(string userName, string password, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoodsCategory", ReplyAction="http://tempuri.org/IEliteService/GetGoodsCategoryResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsCat[]> GetGoodsCategoryAsync(string userName, string password, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoodsCategoryType", ReplyAction="http://tempuri.org/IEliteService/GetGoodsCategoryTypeResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.GoodsCatType[] GetGoodsCategoryType(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetGoodsCategoryType", ReplyAction="http://tempuri.org/IEliteService/GetGoodsCategoryTypeResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsCatType[]> GetGoodsCategoryTypeAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranches", ReplyAction="http://tempuri.org/IEliteService/GetBranchesResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.BranchInfo[] GetBranches(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranches", ReplyAction="http://tempuri.org/IEliteService/GetBranchesResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchInfo[]> GetBranchesAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMembers", ReplyAction="http://tempuri.org/IEliteService/GetMembersResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.MemberInfo[] GetMembers(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMembers", ReplyAction="http://tempuri.org/IEliteService/GetMembersResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MemberInfo[]> GetMembersAsync(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranchSales", ReplyAction="http://tempuri.org/IEliteService/GetBranchSalesResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.BranchSalesInfo[] GetBranchSales(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranchSales", ReplyAction="http://tempuri.org/IEliteService/GetBranchSalesResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchSalesInfo[]> GetBranchSalesAsync(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetInvoices", ReplyAction="http://tempuri.org/IEliteService/GetInvoicesResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.InvoiceInfo[] GetInvoices(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetInvoices", ReplyAction="http://tempuri.org/IEliteService/GetInvoicesResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.InvoiceInfo[]> GetInvoicesAsync(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetPayroll", ReplyAction="http://tempuri.org/IEliteService/GetPayrollResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.Payroll[] GetPayroll(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetPayroll", ReplyAction="http://tempuri.org/IEliteService/GetPayrollResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.Payroll[]> GetPayrollAsync(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMandeDar", ReplyAction="http://tempuri.org/IEliteService/GetMandeDarResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.MandehFaktor[] GetMandeDar(string userName, string password, int ccmarkazpakhsh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMandeDar", ReplyAction="http://tempuri.org/IEliteService/GetMandeDarResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MandehFaktor[]> GetMandeDarAsync(string userName, string password, int ccmarkazpakhsh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMemberReceipts", ReplyAction="http://tempuri.org/IEliteService/GetMemberReceiptsResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.MemberReceiptInfo[] GetMemberReceipts(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetMemberReceipts", ReplyAction="http://tempuri.org/IEliteService/GetMemberReceiptsResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MemberReceiptInfo[]> GetMemberReceiptsAsync(string userName, string password, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranchReceipts", ReplyAction="http://tempuri.org/IEliteService/GetBranchReceiptsResponse")]
        Neutrino.External.Sevices.neu.eliteco.services.BranchReceiptInfo[] GetBranchReceipts(string userName, string password, int year, int month, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEliteService/GetBranchReceipts", ReplyAction="http://tempuri.org/IEliteService/GetBranchReceiptsResponse")]
        System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchReceiptInfo[]> GetBranchReceiptsAsync(string userName, string password, int year, int month, int branchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEliteServiceChannel : Neutrino.External.Sevices.neu.eliteco.services.IEliteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EliteServiceClient : System.ServiceModel.ClientBase<Neutrino.External.Sevices.neu.eliteco.services.IEliteService>, Neutrino.External.Sevices.neu.eliteco.services.IEliteService {
        
        public EliteServiceClient() {
        }
        
        public EliteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EliteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EliteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EliteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.CompanyInfo[] GetCompanies(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate) {
            return base.Channel.GetCompanies(userName, password, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.CompanyInfo[]> GetCompaniesAsync(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate) {
            return base.Channel.GetCompaniesAsync(userName, password, startDate, endDate);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.GoodsInfo[] GetGoods(string userName, string password, int companyId) {
            return base.Channel.GetGoods(userName, password, companyId);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsInfo[]> GetGoodsAsync(string userName, string password, int companyId) {
            return base.Channel.GetGoodsAsync(userName, password, companyId);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.GoodsCat[] GetGoodsCategory(string userName, string password, int companyId) {
            return base.Channel.GetGoodsCategory(userName, password, companyId);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsCat[]> GetGoodsCategoryAsync(string userName, string password, int companyId) {
            return base.Channel.GetGoodsCategoryAsync(userName, password, companyId);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.GoodsCatType[] GetGoodsCategoryType(string userName, string password) {
            return base.Channel.GetGoodsCategoryType(userName, password);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.GoodsCatType[]> GetGoodsCategoryTypeAsync(string userName, string password) {
            return base.Channel.GetGoodsCategoryTypeAsync(userName, password);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.BranchInfo[] GetBranches(string userName, string password) {
            return base.Channel.GetBranches(userName, password);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchInfo[]> GetBranchesAsync(string userName, string password) {
            return base.Channel.GetBranchesAsync(userName, password);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.MemberInfo[] GetMembers(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate, int branchId) {
            return base.Channel.GetMembers(userName, password, startDate, endDate, branchId);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MemberInfo[]> GetMembersAsync(string userName, string password, System.Nullable<System.DateTime> startDate, System.DateTime endDate, int branchId) {
            return base.Channel.GetMembersAsync(userName, password, startDate, endDate, branchId);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.BranchSalesInfo[] GetBranchSales(string userName, string password, int year, int month) {
            return base.Channel.GetBranchSales(userName, password, year, month);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchSalesInfo[]> GetBranchSalesAsync(string userName, string password, int year, int month) {
            return base.Channel.GetBranchSalesAsync(userName, password, year, month);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.InvoiceInfo[] GetInvoices(string userName, string password, int year, int month) {
            return base.Channel.GetInvoices(userName, password, year, month);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.InvoiceInfo[]> GetInvoicesAsync(string userName, string password, int year, int month) {
            return base.Channel.GetInvoicesAsync(userName, password, year, month);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.Payroll[] GetPayroll(string userName, string password, int year, int month) {
            return base.Channel.GetPayroll(userName, password, year, month);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.Payroll[]> GetPayrollAsync(string userName, string password, int year, int month) {
            return base.Channel.GetPayrollAsync(userName, password, year, month);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.MandehFaktor[] GetMandeDar(string userName, string password, int ccmarkazpakhsh) {
            return base.Channel.GetMandeDar(userName, password, ccmarkazpakhsh);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MandehFaktor[]> GetMandeDarAsync(string userName, string password, int ccmarkazpakhsh) {
            return base.Channel.GetMandeDarAsync(userName, password, ccmarkazpakhsh);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.MemberReceiptInfo[] GetMemberReceipts(string userName, string password, int year, int month) {
            return base.Channel.GetMemberReceipts(userName, password, year, month);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.MemberReceiptInfo[]> GetMemberReceiptsAsync(string userName, string password, int year, int month) {
            return base.Channel.GetMemberReceiptsAsync(userName, password, year, month);
        }
        
        public Neutrino.External.Sevices.neu.eliteco.services.BranchReceiptInfo[] GetBranchReceipts(string userName, string password, int year, int month, int branchId) {
            return base.Channel.GetBranchReceipts(userName, password, year, month, branchId);
        }
        
        public System.Threading.Tasks.Task<Neutrino.External.Sevices.neu.eliteco.services.BranchReceiptInfo[]> GetBranchReceiptsAsync(string userName, string password, int year, int month, int branchId) {
            return base.Channel.GetBranchReceiptsAsync(userName, password, year, month, branchId);
        }
    }
}
