// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GoalStep_StepItem_Alter_Columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoalStep_StepItem_Alter_Columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201710060535189_GoalStep_StepItem_Alter_Columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
