// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGoalType_GoodsCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGoalType_GoodsCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201711072008061_AddGoalType_GoodsCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
