// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterRelation_GoalStep_StepItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterRelation_GoalStep_StepItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201710060616108_AlterRelation_GoalStep_StepItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
