// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CasecadeDelete_GoalStep_GoalStepInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CasecadeDelete_GoalStep_GoalStepInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201710130750596_CasecadeDelete_GoalStep_GoalStepInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
