// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIsActiveGoalStep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsActiveGoalStep));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071938222_addIsActiveGoalStep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
