// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rename_remove_isactive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_remove_isactive));
        
        string IMigrationMetadata.Id
        {
            get { return "201811151726440_rename_remove_isactive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
