// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_dateTOyear_month_goalfulfillment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_dateTOyear_month_goalfulfillment));
        
        string IMigrationMetadata.Id
        {
            get { return "201811151758500_change_dateTOyear_month_goalfulfillment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
