namespace Neutrino.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addLastUpdated : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ApplicationAction", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.ApplicationAction", "EditorId", c => c.Int());
            AddColumn("dbo.Permission", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Permission", "EditorId", c => c.Int());
            AddColumn("dbo.Role", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Role", "EditorId", c => c.Int());
            AddColumn("dbo.UserRole", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserRole", "EditorId", c => c.Int());
            AddColumn("dbo.User", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.User", "EditorId", c => c.Int());
            AddColumn("dbo.UserClaim", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserClaim", "EditorId", c => c.Int());
            AddColumn("dbo.AppMenu", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.AppMenu", "EditorId", c => c.Int());
            AddColumn("dbo.AppSetting", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.AppSetting", "EditorId", c => c.Int());
            AddColumn("dbo.Branch", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Branch", "EditorId", c => c.Int());
            AddColumn("dbo.BranchGoal", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.BranchGoal", "EditorId", c => c.Int());
            AddColumn("dbo.Goal", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Goal", "EditorId", c => c.Int());
            AddColumn("dbo.Commission", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Commission", "EditorId", c => c.Int());
            AddColumn("dbo.CommissionStatus", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.CommissionStatus", "EditorId", c => c.Int());
            AddColumn("dbo.Company", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Company", "EditorId", c => c.Int());
            AddColumn("dbo.CompanyType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.CompanyType", "EditorId", c => c.Int());
            AddColumn("dbo.Goods", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Goods", "EditorId", c => c.Int());
            AddColumn("dbo.GoalGoodsCategory", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalGoodsCategory", "EditorId", c => c.Int());
            AddColumn("dbo.GoalGoodsCategoryType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalGoodsCategoryType", "EditorId", c => c.Int());
            AddColumn("dbo.GoalType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalType", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsCategory", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsCategory", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsCategoryType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsCategoryType", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsPrice", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsPrice", "EditorId", c => c.Int());
            AddColumn("dbo.SupplierType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.SupplierType", "EditorId", c => c.Int());
            AddColumn("dbo.TherapeuticType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.TherapeuticType", "EditorId", c => c.Int());
            AddColumn("dbo.ComputingType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.ComputingType", "EditorId", c => c.Int());
            AddColumn("dbo.GoalStep", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalStep", "EditorId", c => c.Int());
            AddColumn("dbo.GoalStepItemInfo", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalStepItemInfo", "EditorId", c => c.Int());
            AddColumn("dbo.GoalStepActionType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalStepActionType", "EditorId", c => c.Int());
            AddColumn("dbo.TotalSalesGoalRange", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.TotalSalesGoalRange", "EditorId", c => c.Int());
            AddColumn("dbo.GoalFulfillment", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalFulfillment", "EditorId", c => c.Int());
            AddColumn("dbo.BranchQuantityCondition", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.BranchQuantityCondition", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsQuantityCondition", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsQuantityCondition", "EditorId", c => c.Int());
            AddColumn("dbo.QuantityCondition", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.QuantityCondition", "EditorId", c => c.Int());
            AddColumn("dbo.BranchReceipt", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.BranchReceipt", "EditorId", c => c.Int());
            AddColumn("dbo.BranchSales", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.BranchSales", "EditorId", c => c.Int());
            AddColumn("dbo.CondemnationType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.CondemnationType", "EditorId", c => c.Int());
            AddColumn("dbo.CostCoefficient", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.CostCoefficient", "EditorId", c => c.Int());
            AddColumn("dbo.DataSyncStatus", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.DataSyncStatus", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsPromotion", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsPromotion", "EditorId", c => c.Int());
            AddColumn("dbo.GoodsScore", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoodsScore", "EditorId", c => c.Int());
            AddColumn("dbo.Invoice", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Invoice", "EditorId", c => c.Int());
            AddColumn("dbo.MemberReceipt", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.MemberReceipt", "EditorId", c => c.Int());
            AddColumn("dbo.Member", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.Member", "EditorId", c => c.Int());
            AddColumn("dbo.PositionType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.PositionType", "EditorId", c => c.Int());
            AddColumn("dbo.OrgStructure", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.OrgStructure", "EditorId", c => c.Int());
            AddColumn("dbo.OtherRewardType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.OtherRewardType", "EditorId", c => c.Int());
            AddColumn("dbo.MemberPayroll", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.MemberPayroll", "EditorId", c => c.Int());
            AddColumn("dbo.PersonelShare", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.PersonelShare", "EditorId", c => c.Int());
            AddColumn("dbo.RewardType", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.RewardType", "EditorId", c => c.Int());
            AddColumn("dbo.StockInventory", "LastUpdated", c => c.DateTime(nullable: false));
            AddColumn("dbo.StockInventory", "EditorId", c => c.Int());
            AlterColumn("dbo.ApplicationAction", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Permission", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Role", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UserRole", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.User", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UserClaim", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.AppMenu", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.AppSetting", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Branch", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BranchGoal", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Goal", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Commission", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CommissionStatus", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Company", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CompanyType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Goods", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalGoodsCategory", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalGoodsCategoryType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsCategory", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsCategoryType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsPrice", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SupplierType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.TherapeuticType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ComputingType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalStep", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalStepItemInfo", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalStepActionType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.TotalSalesGoalRange", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoalFulfillment", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BranchQuantityCondition", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsQuantityCondition", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.QuantityCondition", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BranchReceipt", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BranchSales", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CondemnationType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CostCoefficient", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.DataSyncStatus", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsPromotion", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GoodsScore", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Invoice", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MemberReceipt", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Member", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PositionType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrgStructure", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OtherRewardType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MemberPayroll", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonelShare", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RewardType", "DateCreated", c => c.DateTime(nullable: false));
            AlterColumn("dbo.StockInventory", "DateCreated", c => c.DateTime(nullable: false));
            CreateIndex("dbo.Goods", "RefId", unique: true);
        }
        
        public override void Down()
        {
            DropIndex("dbo.Goods", new[] { "RefId" });
            AlterColumn("dbo.StockInventory", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.RewardType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.PersonelShare", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.MemberPayroll", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.OtherRewardType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.OrgStructure", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.PositionType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Member", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.MemberReceipt", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Invoice", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsScore", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsPromotion", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.DataSyncStatus", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.CostCoefficient", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.CondemnationType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.BranchSales", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.BranchReceipt", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.QuantityCondition", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsQuantityCondition", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.BranchQuantityCondition", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalFulfillment", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.TotalSalesGoalRange", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalStepActionType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalStepItemInfo", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalStep", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.ComputingType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.TherapeuticType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.SupplierType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsPrice", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsCategoryType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoodsCategory", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalGoodsCategoryType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.GoalGoodsCategory", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Goods", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.CompanyType", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Company", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.CommissionStatus", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Commission", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Goal", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.BranchGoal", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Branch", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.AppSetting", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.AppMenu", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.UserClaim", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.User", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.UserRole", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Role", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.Permission", "DateCreated", c => c.DateTime());
            AlterColumn("dbo.ApplicationAction", "DateCreated", c => c.DateTime());
            DropColumn("dbo.StockInventory", "EditorId");
            DropColumn("dbo.StockInventory", "LastUpdated");
            DropColumn("dbo.RewardType", "EditorId");
            DropColumn("dbo.RewardType", "LastUpdated");
            DropColumn("dbo.PersonelShare", "EditorId");
            DropColumn("dbo.PersonelShare", "LastUpdated");
            DropColumn("dbo.MemberPayroll", "EditorId");
            DropColumn("dbo.MemberPayroll", "LastUpdated");
            DropColumn("dbo.OtherRewardType", "EditorId");
            DropColumn("dbo.OtherRewardType", "LastUpdated");
            DropColumn("dbo.OrgStructure", "EditorId");
            DropColumn("dbo.OrgStructure", "LastUpdated");
            DropColumn("dbo.PositionType", "EditorId");
            DropColumn("dbo.PositionType", "LastUpdated");
            DropColumn("dbo.Member", "EditorId");
            DropColumn("dbo.Member", "LastUpdated");
            DropColumn("dbo.MemberReceipt", "EditorId");
            DropColumn("dbo.MemberReceipt", "LastUpdated");
            DropColumn("dbo.Invoice", "EditorId");
            DropColumn("dbo.Invoice", "LastUpdated");
            DropColumn("dbo.GoodsScore", "EditorId");
            DropColumn("dbo.GoodsScore", "LastUpdated");
            DropColumn("dbo.GoodsPromotion", "EditorId");
            DropColumn("dbo.GoodsPromotion", "LastUpdated");
            DropColumn("dbo.DataSyncStatus", "EditorId");
            DropColumn("dbo.DataSyncStatus", "LastUpdated");
            DropColumn("dbo.CostCoefficient", "EditorId");
            DropColumn("dbo.CostCoefficient", "LastUpdated");
            DropColumn("dbo.CondemnationType", "EditorId");
            DropColumn("dbo.CondemnationType", "LastUpdated");
            DropColumn("dbo.BranchSales", "EditorId");
            DropColumn("dbo.BranchSales", "LastUpdated");
            DropColumn("dbo.BranchReceipt", "EditorId");
            DropColumn("dbo.BranchReceipt", "LastUpdated");
            DropColumn("dbo.QuantityCondition", "EditorId");
            DropColumn("dbo.QuantityCondition", "LastUpdated");
            DropColumn("dbo.GoodsQuantityCondition", "EditorId");
            DropColumn("dbo.GoodsQuantityCondition", "LastUpdated");
            DropColumn("dbo.BranchQuantityCondition", "EditorId");
            DropColumn("dbo.BranchQuantityCondition", "LastUpdated");
            DropColumn("dbo.GoalFulfillment", "EditorId");
            DropColumn("dbo.GoalFulfillment", "LastUpdated");
            DropColumn("dbo.TotalSalesGoalRange", "EditorId");
            DropColumn("dbo.TotalSalesGoalRange", "LastUpdated");
            DropColumn("dbo.GoalStepActionType", "EditorId");
            DropColumn("dbo.GoalStepActionType", "LastUpdated");
            DropColumn("dbo.GoalStepItemInfo", "EditorId");
            DropColumn("dbo.GoalStepItemInfo", "LastUpdated");
            DropColumn("dbo.GoalStep", "EditorId");
            DropColumn("dbo.GoalStep", "LastUpdated");
            DropColumn("dbo.ComputingType", "EditorId");
            DropColumn("dbo.ComputingType", "LastUpdated");
            DropColumn("dbo.TherapeuticType", "EditorId");
            DropColumn("dbo.TherapeuticType", "LastUpdated");
            DropColumn("dbo.SupplierType", "EditorId");
            DropColumn("dbo.SupplierType", "LastUpdated");
            DropColumn("dbo.GoodsPrice", "EditorId");
            DropColumn("dbo.GoodsPrice", "LastUpdated");
            DropColumn("dbo.GoodsCategoryType", "EditorId");
            DropColumn("dbo.GoodsCategoryType", "LastUpdated");
            DropColumn("dbo.GoodsCategory", "EditorId");
            DropColumn("dbo.GoodsCategory", "LastUpdated");
            DropColumn("dbo.GoalType", "EditorId");
            DropColumn("dbo.GoalType", "LastUpdated");
            DropColumn("dbo.GoalGoodsCategoryType", "EditorId");
            DropColumn("dbo.GoalGoodsCategoryType", "LastUpdated");
            DropColumn("dbo.GoalGoodsCategory", "EditorId");
            DropColumn("dbo.GoalGoodsCategory", "LastUpdated");
            DropColumn("dbo.Goods", "EditorId");
            DropColumn("dbo.Goods", "LastUpdated");
            DropColumn("dbo.CompanyType", "EditorId");
            DropColumn("dbo.CompanyType", "LastUpdated");
            DropColumn("dbo.Company", "EditorId");
            DropColumn("dbo.Company", "LastUpdated");
            DropColumn("dbo.CommissionStatus", "EditorId");
            DropColumn("dbo.CommissionStatus", "LastUpdated");
            DropColumn("dbo.Commission", "EditorId");
            DropColumn("dbo.Commission", "LastUpdated");
            DropColumn("dbo.Goal", "EditorId");
            DropColumn("dbo.Goal", "LastUpdated");
            DropColumn("dbo.BranchGoal", "EditorId");
            DropColumn("dbo.BranchGoal", "LastUpdated");
            DropColumn("dbo.Branch", "EditorId");
            DropColumn("dbo.Branch", "LastUpdated");
            DropColumn("dbo.AppSetting", "EditorId");
            DropColumn("dbo.AppSetting", "LastUpdated");
            DropColumn("dbo.AppMenu", "EditorId");
            DropColumn("dbo.AppMenu", "LastUpdated");
            DropColumn("dbo.UserClaim", "EditorId");
            DropColumn("dbo.UserClaim", "LastUpdated");
            DropColumn("dbo.User", "EditorId");
            DropColumn("dbo.User", "LastUpdated");
            DropColumn("dbo.UserRole", "EditorId");
            DropColumn("dbo.UserRole", "LastUpdated");
            DropColumn("dbo.Role", "EditorId");
            DropColumn("dbo.Role", "LastUpdated");
            DropColumn("dbo.Permission", "EditorId");
            DropColumn("dbo.Permission", "LastUpdated");
            DropColumn("dbo.ApplicationAction", "EditorId");
            DropColumn("dbo.ApplicationAction", "LastUpdated");
        }
    }
}
