// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rename_branchbenefit_branchgoal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_branchbenefit_branchgoal));
        
        string IMigrationMetadata.Id
        {
            get { return "201811081743134_rename_branchbenefit_branchgoal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
