// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addYearMonth_Commission_addStartEndDate_Inputs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addYearMonth_Commission_addStartEndDate_Inputs));
        
        string IMigrationMetadata.Id
        {
            get { return "201811071756539_addYearMonth_Commission_addStartEndDate_Inputs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
