// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFulfillPercent_branchgoalpromotion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFulfillPercent_branchgoalpromotion));
        
        string IMigrationMetadata.Id
        {
            get { return "201905222008576_addFulfillPercent_branchgoalpromotion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
