// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addQuantityConditionTypeId_alterQuantityCondition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQuantityConditionTypeId_alterQuantityCondition));
        
        string IMigrationMetadata.Id
        {
            get { return "201904121443503_addQuantityConditionTypeId_alterQuantityCondition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
