// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alterApplicationAction_removeparentid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterApplicationAction_removeparentid));
        
        string IMigrationMetadata.Id
        {
            get { return "201905120501001_alterApplicationAction_removeparentid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
