// <auto-generated />
namespace Neutrino.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rename_memberShare_memberPromotion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_memberShare_memberPromotion));
        
        string IMigrationMetadata.Id
        {
            get { return "201907211843010_rename_memberShare_memberPromotion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
